DROP TABLE IF EXISTS DMA_SAL_ACHV_DATA.dma_sal_achv_shd_act_fee_detail_his ;
CREATE TABLE DMA_SAL_ACHV_DATA.dma_sal_achv_shd_act_fee_detail_his (
  stat_dt VARCHAR(10) DEFAULT NULL               COMMENT '[统计日期]',
  business_id VARCHAR(50) DEFAULT NULL           COMMENT '[业务编号]',
  first_car_business_id VARCHAR(50) DEFAULT NULL COMMENT '[原业务单号]',
  car_business_after_id VARCHAR(50) DEFAULT NULL COMMENT '[当前还款期数]',
  car_business_after_defer VARCHAR(50) DEFAULT NULL COMMENT '[展期业务编号]',
  out_id BIGINT(11) NOT NULL DEFAULT '0'            COMMENT '[还款计划次数]',
  overdueDays BIGINT(11) DEFAULT NULL               COMMENT '[逾期天数]',
  overdueDays_tot DECIMAL(42,0) DEFAULT NULL        COMMENT '[逾期天数之和]',
  is_defer VARCHAR(2) NOT NULL DEFAULT ''           COMMENT '[类型:展期/新增]',
  out_date VARCHAR(10) DEFAULT NULL 		    COMMENT '[出款日期/展期日期]',
  borrow_money DECIMAL(12,2) DEFAULT NULL           COMMENT '[借款金额]',
  oddcorpus DECIMAL(12,2) NOT NULL DEFAULT '0.00'   COMMENT '[剩余本金]',
  business_type VARCHAR(100) DEFAULT NULL           COMMENT '[业务类型]',
  ovd_status VARCHAR(4) DEFAULT NULL                COMMENT '[逾期状态]',
  customer_name VARCHAR(100) DEFAULT NULL           COMMENT '客户名称',
  customer_list VARCHAR(500) DEFAULT NULL           COMMENT '所有客户姓名,已逗号隔开',
  is_issue VARCHAR(1) DEFAULT NULL                  COMMENT '[是否上标]',
  area_nm VARCHAR(50) NOT NULL DEFAULT ''           COMMENT '[区域]',
  branch_nm VARCHAR(50) NOT NULL DEFAULT ''         COMMENT '[分公司]',
  repay_type_nm VARCHAR(50) NOT NULL DEFAULT ''     COMMENT '[还款方式]',
  is_platform VARCHAR(4) DEFAULT NULL               COMMENT '[所属平台：团贷网/你我金融]',
  borrow_date VARCHAR(10) DEFAULT NULL                                      COMMENT '应收日期',        
  ShouldRecePrincipa DECIMAL(12,2) NOT NULL DEFAULT '0.00'                  COMMENT '应收本金（元）',  
  ShouldReceAccrual DECIMAL(12,2) NOT NULL DEFAULT '0.00'                   COMMENT '应收利息（元）',  
  should_repay_service DECIMAL(10,2) NOT NULL DEFAULT '0.00'                COMMENT '应收分公司服务费',
  should_little_tot DECIMAL(12,2) NOT NULL DEFAULT '0.00'                   COMMENT '应收小计',        
  should_other_money DECIMAL(12,2) NOT NULL DEFAULT '0.00'                  COMMENT '应收其他费用',    
  should_tot DECIMAL(12,2) NOT NULL DEFAULT '0.00'                          COMMENT '应收合计',        
  fatct_replayDate VARCHAR(10) DEFAULT NULL                                 COMMENT '实收日期',        
  ActualRecePrincipa DECIMAL(12,2) NOT NULL DEFAULT '0.00'                  COMMENT '实收本金',        
  ActualReceAccrual DECIMAL(12,2) NOT NULL DEFAULT '0.00'                   COMMENT '实收利息',        
  fact_service DECIMAL(12,2) NOT NULL DEFAULT '0.00'                        COMMENT '实收分公司服务费',
  ActualOther DECIMAL(12,2) NOT NULL DEFAULT '0.00'                         COMMENT '实收其他费用',    
  act_little_tot DOUBLE NOT NULL DEFAULT '0'                                COMMENT '实收小计',        
  act_tot DOUBLE NOT NULL DEFAULT '0'                                       COMMENT '实收合计', 
  dw_src_sys VARCHAR(10) NOT NULL DEFAULT '',
  dw_src_tbl VARCHAR(500) NOT NULL DEFAULT '',
  dw_ins_tm DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  dw_upd_tm DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  dw_ins_usr VARCHAR(5) NOT NULL DEFAULT '',
  dw_upd_usr VARCHAR(5) NOT NULL DEFAULT '',
  part_dt DATETIME DEFAULT NULL,
  KEY idx_business_id (business_id),
  KEY idx_out_id (out_id),
  KEY idx_first_car_business_id(first_car_business_id)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT '应收实收台账his表'
/*!50100 PARTITION BY RANGE (TO_DAYS(part_dt))
(PARTITION dma_sal_achv_shd_act_fee_detail_his VALUES LESS THAN (737241) ENGINE = InnoDB,
 PARTITION dma_sal_achv_shd_act_fee_detail_his_2018_07_01 VALUES LESS THAN (737242) ENGINE = InnoDB,
 PARTITION dma_sal_achv_shd_act_fee_detail_his_2018_07_02 VALUES LESS THAN (737243) ENGINE = InnoDB,
 PARTITION dma_sal_achv_shd_act_fee_detail_his_2018_07_03 VALUES LESS THAN (737244) ENGINE = InnoDB,
 PARTITION dma_sal_achv_shd_act_fee_detail_his_2018_07_04 VALUES LESS THAN (737245) ENGINE = InnoDB,
 PARTITION dma_sal_achv_shd_act_fee_detail_his_2018_07_05 VALUES LESS THAN (737246) ENGINE = InnoDB,
 PARTITION dma_sal_achv_shd_act_fee_detail_his_2018_07_06 VALUES LESS THAN (737247) ENGINE = InnoDB,
 PARTITION dma_sal_achv_shd_act_fee_detail_his_2018_07_07 VALUES LESS THAN (737248) ENGINE = InnoDB,
 PARTITION dma_sal_achv_shd_act_fee_detail_his_2018_07_08 VALUES LESS THAN (737249) ENGINE = InnoDB,
 PARTITION dma_sal_achv_shd_act_fee_detail_his_2018_07_09 VALUES LESS THAN (737250) ENGINE = InnoDB,
 PARTITION dma_sal_achv_shd_act_fee_detail_his_2018_07_10 VALUES LESS THAN (737251) ENGINE = InnoDB,
 PARTITION dma_sal_achv_shd_act_fee_detail_his_2018_07_11 VALUES LESS THAN (737252) ENGINE = InnoDB,
 PARTITION dma_sal_achv_shd_act_fee_detail_his_2018_07_12 VALUES LESS THAN (737253) ENGINE = InnoDB,
 PARTITION dma_sal_achv_shd_act_fee_detail_his_2018_07_13 VALUES LESS THAN (737254) ENGINE = InnoDB,
 PARTITION dma_sal_achv_shd_act_fee_detail_his_2018_07_14 VALUES LESS THAN (737255) ENGINE = InnoDB,
 PARTITION dma_sal_achv_shd_act_fee_detail_his_2018_07_15 VALUES LESS THAN (737256) ENGINE = InnoDB,
 PARTITION dma_sal_achv_shd_act_fee_detail_his_2018_07_16 VALUES LESS THAN (737257) ENGINE = InnoDB) */
 ;
 
 
DROP TABLE IF EXISTS DMA_SAL_ACHV_DATA.dma_sal_achv_shd_act_fee_detail ;
CREATE TABLE DMA_SAL_ACHV_DATA.dma_sal_achv_shd_act_fee_detail (
  stat_dt VARCHAR(10) DEFAULT NULL               COMMENT '[统计日期]',
  business_id VARCHAR(50) DEFAULT NULL           COMMENT '[业务编号]',
  first_car_business_id VARCHAR(50) DEFAULT NULL COMMENT '[原业务单号]',
  car_business_after_id VARCHAR(50) DEFAULT NULL COMMENT '[当前还款期数]',
  car_business_after_defer VARCHAR(50) DEFAULT NULL COMMENT '[展期业务编号]',
  out_id BIGINT(11) NOT NULL DEFAULT '0'            COMMENT '[还款计划次数]',
  overdueDays BIGINT(11) DEFAULT NULL               COMMENT '[逾期天数]',
  overdueDays_tot DECIMAL(42,0) DEFAULT NULL        COMMENT '[逾期天数之和]',
  is_defer VARCHAR(2) NOT NULL DEFAULT ''           COMMENT '[类型:展期/新增]',
  out_date VARCHAR(10) DEFAULT NULL 		    COMMENT '[出款日期/展期日期]',
  borrow_money DECIMAL(12,2) DEFAULT NULL           COMMENT '[借款金额]',
  oddcorpus DECIMAL(12,2) NOT NULL DEFAULT '0.00'   COMMENT '[剩余本金]',
  business_type VARCHAR(100) DEFAULT NULL           COMMENT '[业务类型]',
  ovd_status VARCHAR(4) DEFAULT NULL                COMMENT '[逾期状态]',
  customer_name VARCHAR(100) DEFAULT NULL           COMMENT '客户名称',
  customer_list VARCHAR(500) DEFAULT NULL           COMMENT '所有客户姓名,已逗号隔开',
  is_issue VARCHAR(1) DEFAULT NULL                  COMMENT '[是否上标]',
  area_nm VARCHAR(50) NOT NULL DEFAULT ''           COMMENT '[区域]',
  branch_nm VARCHAR(50) NOT NULL DEFAULT ''         COMMENT '[分公司]',
  repay_type_nm VARCHAR(50) NOT NULL DEFAULT ''     COMMENT '[还款方式]',
  is_platform VARCHAR(4) DEFAULT NULL               COMMENT '[所属平台：团贷网/你我金融]',
  borrow_date VARCHAR(10) DEFAULT NULL                                      COMMENT '应收日期',        
  ShouldRecePrincipa DECIMAL(12,2) NOT NULL DEFAULT '0.00'                  COMMENT '应收本金（元）',  
  ShouldReceAccrual DECIMAL(12,2) NOT NULL DEFAULT '0.00'                   COMMENT '应收利息（元）',  
  should_repay_service DECIMAL(10,2) NOT NULL DEFAULT '0.00'                COMMENT '应收分公司服务费',
  should_little_tot DECIMAL(12,2) NOT NULL DEFAULT '0.00'                   COMMENT '应收小计',        
  should_other_money DECIMAL(12,2) NOT NULL DEFAULT '0.00'                  COMMENT '应收其他费用',    
  should_tot DECIMAL(12,2) NOT NULL DEFAULT '0.00'                          COMMENT '应收合计',        
  fatct_replayDate VARCHAR(10) DEFAULT NULL                                 COMMENT '实收日期',        
  ActualRecePrincipa DECIMAL(12,2) NOT NULL DEFAULT '0.00'                  COMMENT '实收本金',        
  ActualReceAccrual DECIMAL(12,2) NOT NULL DEFAULT '0.00'                   COMMENT '实收利息',        
  fact_service DECIMAL(12,2) NOT NULL DEFAULT '0.00'                        COMMENT '实收分公司服务费',
  ActualOther DECIMAL(12,2) NOT NULL DEFAULT '0.00'                         COMMENT '实收其他费用',    
  act_little_tot DOUBLE NOT NULL DEFAULT '0'                                COMMENT '实收小计',        
  act_tot DOUBLE NOT NULL DEFAULT '0'                                       COMMENT '实收合计', 
  dw_src_sys VARCHAR(10) NOT NULL DEFAULT '',
  dw_src_tbl VARCHAR(500) NOT NULL DEFAULT '',
  dw_ins_tm DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  dw_upd_tm DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  dw_ins_usr VARCHAR(5) NOT NULL DEFAULT '',
  dw_upd_usr VARCHAR(5) NOT NULL DEFAULT '',
  KEY idx_car_business_after_id(first_car_business_id,car_business_after_id),
  KEY idx_after_out (first_car_business_id,out_id),
  KEY idx_car_business_after_defer (car_business_after_defer),
  KEY idx_borrow_date (borrow_date),
  KEY idx_fatct_replayDate (fatct_replayDate),
  KEY idx_out_date (out_date),
  KEY idx_first_car_business_id (first_car_business_id)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT '应收实收台账表'
 ; 