-- 财务收入表 （目前： 房速贷和车易贷整合在一起 展示 一点是否整合待定）

DROP  TABLE IF EXISTS DMA_CEO_RPT_DATA.`dma_ceo_rpt_fin_revenue_fc`;
CREATE TABLE DMA_CEO_RPT_DATA.`dma_ceo_rpt_fin_revenue_fc`
(
stat_dt       VARCHAR(10)         COMMENT       '统计日期',
actual_repayment_date       VARCHAR(10)         COMMENT       '实收日期',
area_nm       VARCHAR(100)         COMMENT       '片区',
branch_nm       VARCHAR(100)         COMMENT       '分公司',
business_type_nm       VARCHAR(50)         COMMENT       '业务类型',
borrow_limit       VARCHAR(50)         COMMENT       '借款期限',
repay_type_nm       VARCHAR(50)         COMMENT       '还款方式',
business_id       VARCHAR(50)         COMMENT       '业务编号',
customer_nm       VARCHAR(50)         COMMENT       '客户名称',
borrow_amt       DECIMAL(12,2)         COMMENT       '放款额',
comp_mon_srv_amt       DECIMAL(12,2)         COMMENT       '分公司费用:月收服务费(金额)',
comp_one_tm_srv_amt       DECIMAL(12,2)         COMMENT       '分公司费用:一次性服务费（金额）',
mon_srv_pct_amt       DECIMAL(12,2)         COMMENT       '分公司费用:月收服务费(比例)',
agency_amt       DECIMAL(12,2)         COMMENT       '分公司费用:中介费',
admin_amt       DECIMAL(12,2)         COMMENT       '分公司费用:行政综合费',
repay_evaluate_money       DECIMAL(12,2)         COMMENT       '分公司费用:评估费',
gps_cost_amt       DECIMAL(12,2)         COMMENT       '分公司费用:GPS费用',
comp_stop_amt       DECIMAL(12,2)         COMMENT       '分公司费用:停车费',
acct_mgr_amt       DECIMAL(12,2)         COMMENT       '分公司费用:账户管理费',
consult_file_amt       DECIMAL(12,2)         COMMENT       '分公司费用:查档费',
plat_mon_srv_amt       DECIMAL(12,2)         COMMENT       '团贷网平台费用:月收平台费',
plat_one_tm_srv_amt       DECIMAL(12,2)         COMMENT       '团贷网平台费用:一次性收平台费',
one_tm_db_fee       DECIMAL(12,2)         COMMENT       '担保费',
consult_amt       DECIMAL(12,2)         COMMENT       '咨询费',
maintenamce_amt       DECIMAL(12,2)         COMMENT       '保全费',
extsn_nofsh_srv_amt       DECIMAL(12,2)         COMMENT       '展期费用:未结清服务费',
extsn_charge_amt       DECIMAL(12,2)         COMMENT       '展期费用:手续费',
extsn_nofsh_other_amt       DECIMAL(12,2)         COMMENT       '展期费用:未结清其他费用',
current_Breach       DECIMAL(12,2)         COMMENT       '滞纳金',
deferred_pay_amt       DECIMAL(12,2)         COMMENT       '延迟履行金',
day_visit_amt       DECIMAL(12,2)         COMMENT       '结清固定费用:上门费',
fsh_stop_amt       DECIMAL(12,2)         COMMENT       '结清固定费用:停车费',
day_lawyer_amt       DECIMAL(12,2)         COMMENT       '结清固定费用:律师费',
day_adv_settle_amt       DECIMAL(12,2)         COMMENT       '结清固定费用:提前结清违约金',
day_Litigation_amt       DECIMAL(12,2)         COMMENT       '结清固定费用:诉讼费',
day_trail_amt       DECIMAL(12,2)         COMMENT       '结清固定费用:拖车费',
court_accpt_amt       DECIMAL(12,2)         COMMENT       '结清固定费用:案件受理费',
day_ovd_brh_srv_amt       DECIMAL(12,2)         COMMENT       '结清固定费用:逾期分公司服务费',
overdue_acal       DECIMAL(12,2)         COMMENT       '结清固定费用:逾期利息',
day_ovd_income_amt       DECIMAL(12,2)         COMMENT       '结清固定费用:逾期收入',
other_money       DECIMAL(12,2)         COMMENT       '结清固定费用:其他费用',
day_margin_amt       DECIMAL(12,2)         COMMENT       '利差',
dw_src_sys       VARCHAR(50)         COMMENT       '来源系统',
dw_src_tbl       VARCHAR(500)         COMMENT       '来源表',
dw_ins_tm       DATETIME         COMMENT       '插入时间',
dw_upd_tm       DATETIME         COMMENT       '更新时间',
dw_ins_usr       VARCHAR(50)         COMMENT       '插入用户',
dw_upd_usr       VARCHAR(50)         COMMENT       '更新用户',
KEY  idx_business_id(business_id),
KEY  idx_actual_repayment_date(actual_repayment_date),
KEY idx_actual_repayment_date_idx_business_id(business_id,actual_repayment_date),
KEY idx_area_nm(area_nm),
KEY idx_branch_nm(branch_nm),
KEY idx_customer_nm(customer_nm)
)ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='ceo看板财务收入表（房车部分）';


-- 财务收入表 （目前： 房速贷和车易贷整合在一起 展示 一点是否整合待定）

DROP  TABLE IF EXISTS DMA_CEO_RPT_DATA.`dma_ceo_rpt_fin_revenue_fc_his`;
CREATE TABLE DMA_CEO_RPT_DATA.`dma_ceo_rpt_fin_revenue_fc_his`
(
stat_dt       VARCHAR(10)         COMMENT       '统计日期',
actual_repayment_date       VARCHAR(10)         COMMENT       '实收日期',
area_nm       VARCHAR(100)         COMMENT       '片区',
branch_nm       VARCHAR(100)         COMMENT       '分公司',
business_type_nm       VARCHAR(50)         COMMENT       '业务类型',
borrow_limit       VARCHAR(50)         COMMENT       '借款期限',
repay_type_nm       VARCHAR(50)         COMMENT       '还款方式',
business_id       VARCHAR(50)         COMMENT       '业务编号',
customer_nm       VARCHAR(50)         COMMENT       '客户名称',
borrow_amt       DECIMAL(12,2)         COMMENT       '放款额',
comp_mon_srv_amt       DECIMAL(12,2)         COMMENT       '分公司费用:月收服务费(金额)',
comp_one_tm_srv_amt       DECIMAL(12,2)         COMMENT       '分公司费用:一次性服务费（金额）',
mon_srv_pct_amt       DECIMAL(12,2)         COMMENT       '分公司费用:月收服务费(比例)',
agency_amt       DECIMAL(12,2)         COMMENT       '分公司费用:中介费',
admin_amt       DECIMAL(12,2)         COMMENT       '分公司费用:行政综合费',
repay_evaluate_money       DECIMAL(12,2)         COMMENT       '分公司费用:评估费',
gps_cost_amt       DECIMAL(12,2)         COMMENT       '分公司费用:GPS费用',
comp_stop_amt       DECIMAL(12,2)         COMMENT       '分公司费用:停车费',
acct_mgr_amt       DECIMAL(12,2)         COMMENT       '分公司费用:账户管理费',
consult_file_amt       DECIMAL(12,2)         COMMENT       '分公司费用:查档费',
plat_mon_srv_amt       DECIMAL(12,2)         COMMENT       '团贷网平台费用:月收平台费',
plat_one_tm_srv_amt       DECIMAL(12,2)         COMMENT       '团贷网平台费用:一次性收平台费',
one_tm_db_fee       DECIMAL(12,2)         COMMENT       '担保费',
consult_amt       DECIMAL(12,2)         COMMENT       '咨询费',
maintenamce_amt       DECIMAL(12,2)         COMMENT       '保全费',
extsn_nofsh_srv_amt       DECIMAL(12,2)         COMMENT       '展期费用:未结清服务费',
extsn_charge_amt       DECIMAL(12,2)         COMMENT       '展期费用:手续费',
extsn_nofsh_other_amt       DECIMAL(12,2)         COMMENT       '展期费用:未结清其他费用',
current_Breach       DECIMAL(12,2)         COMMENT       '滞纳金',
deferred_pay_amt       DECIMAL(12,2)         COMMENT       '延迟履行金',
day_visit_amt       DECIMAL(12,2)         COMMENT       '结清固定费用:上门费',
fsh_stop_amt       DECIMAL(12,2)         COMMENT       '结清固定费用:停车费',
day_lawyer_amt       DECIMAL(12,2)         COMMENT       '结清固定费用:律师费',
day_adv_settle_amt       DECIMAL(12,2)         COMMENT       '结清固定费用:提前结清违约金',
day_Litigation_amt       DECIMAL(12,2)         COMMENT       '结清固定费用:诉讼费',
day_trail_amt       DECIMAL(12,2)         COMMENT       '结清固定费用:拖车费',
court_accpt_amt       DECIMAL(12,2)         COMMENT       '结清固定费用:案件受理费',
day_ovd_brh_srv_amt       DECIMAL(12,2)         COMMENT       '结清固定费用:逾期分公司服务费',
overdue_acal       DECIMAL(12,2)         COMMENT       '结清固定费用:逾期利息',
day_ovd_income_amt       DECIMAL(12,2)         COMMENT       '结清固定费用:逾期收入',
other_money       DECIMAL(12,2)         COMMENT       '结清固定费用:其他费用',
day_margin_amt       DECIMAL(12,2)         COMMENT       '利差',
dw_src_sys       VARCHAR(50)         COMMENT       '来源系统',
dw_src_tbl       VARCHAR(500)         COMMENT       '来源表',
dw_ins_tm       DATETIME         COMMENT       '插入时间',
dw_upd_tm       DATETIME         COMMENT       '更新时间',
dw_ins_usr       VARCHAR(50)         COMMENT       '插入用户',
dw_upd_usr       VARCHAR(50)         COMMENT       '更新用户',
`part_dt` DATETIME DEFAULT NULL COMMENT '分区日期',
KEY  idx_business_id(business_id),
KEY  idx_actual_repayment_date(actual_repayment_date),
KEY idx_part_dt(part_dt)
)
ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='ceo看板财务收入his表（房车部分）'
/*!50100 PARTITION BY RANGE (TO_DAYS(part_dt))
( PARTITION dma_ceo_rpt_fin_revenue_fc_his_2018_05_01 VALUES LESS THAN (737181) ENGINE = INNODB,
 PARTITION dma_ceo_rpt_fin_revenue_fc_his_2018_05_02 VALUES LESS THAN (737182) ENGINE = INNODB,
 PARTITION dma_ceo_rpt_fin_revenue_fc_his_2018_05_03 VALUES LESS THAN (737183) ENGINE = INNODB,
 PARTITION dma_ceo_rpt_fin_revenue_fc_his_2018_05_04 VALUES LESS THAN (737184) ENGINE = INNODB,
 PARTITION dma_ceo_rpt_fin_revenue_fc_his_2018_05_05 VALUES LESS THAN (737185) ENGINE = INNODB,
 PARTITION dma_ceo_rpt_fin_revenue_fc_his_2018_05_06 VALUES LESS THAN (737186) ENGINE = INNODB,
 PARTITION dma_ceo_rpt_fin_revenue_fc_his_2018_05_07 VALUES LESS THAN (737187) ENGINE = INNODB,
 PARTITION dma_ceo_rpt_fin_revenue_fc_his_2018_05_08 VALUES LESS THAN (737188) ENGINE = INNODB,
 PARTITION dma_ceo_rpt_fin_revenue_fc_his_2018_05_09 VALUES LESS THAN (737189) ENGINE = INNODB,
 PARTITION dma_ceo_rpt_fin_revenue_fc_his_2018_05_10 VALUES LESS THAN (737190) ENGINE = INNODB) */
; 
 



