create table dma_sal_achv_fsd_out_tra_sum
(
stat_dt       varchar(10)         comment       '统计日期',
area_nm       varchar(100)         comment       '区域',
branch_nm       varchar(100)         comment       '分公司',
new_out_cnt       int(11)         comment       '净新增出款单数',
new_out_amt       decimal(12,2)         comment       '净新增业务出款额',
new_apl_cnt       int(11)         comment       '净新增申请单数量',
new_pass_cnt       int(11)         comment       '净新增通过件数量',
new_sign_cnt       int(11)         comment       '净新增签约件数',
etsn_amt       decimal(12,2)         comment       '展期业务金额',
ode_cnt       int(11)         comment       '逾期笔数',
ode_prpa       decimal(12,2)         comment       '逾期本金',
ode_acal       decimal(12,2)         comment       '逾期利息',
ode_plty       decimal(12,2)         comment       '逾期违约金',
settle_cnt       int(11)         comment       '结清笔数',
bef_settle_prpa       decimal(12,2)         comment       '提前结清金额',
bef_settle_plty       decimal(12,2)         comment       '提前结清违约金',
nml_settle_prpa       decimal(12,2)         comment       '到期结清金额',
ode_settle_prpa       decimal(12,2)         comment       '逾期结清金额',
one_tm_xzzh_fee       decimal(12,2)         comment       '行政综合费',
new_pre_serv_fee_inc       decimal(12,2)         comment       '净新增业务首期前置服务费创收',
new_one_tm_fee       decimal(12,2)         comment       '净新增业务一次性收取费用',
new_mon_fee       decimal(12,2)         comment       '净新增业务按月收取费用',
etsn_pre_serv_fee_inc       decimal(12,2)         comment       '展期业务首期前置服务费创收',
etsn_one_tm_fee       decimal(12,2)         comment       '展期业务一次性收取费用',
etsn_mon_fee       decimal(12,2)         comment       '展期业务按月收取费用',
input_dt       varchar(10)         comment       '受理日期',
update_dt       varchar(10)         comment       '更新日期',
dw_src_sys       varchar(50)         comment       '来源系统',
dw_src_tbl       varchar(500)         comment       '来源表',
dw_ins_tm       datetime         comment       '插入时间',
dw_upd_tm       datetime         comment       '更新时间',
dw_ins_usr       varchar(50)         comment       '插入用户',
dw_upd_usr       varchar(50)         comment       '更新用户'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='房速贷出款业务跟踪汇总表';