DROP  TABLE IF EXISTS DMA_CEO_RPT_DATA.dma_ceo_rpt_overdue_detail;
CREATE TABLE DMA_CEO_RPT_DATA.dma_ceo_rpt_overdue_detail
(
stat_dt       VARCHAR(10)         COMMENT       '跑批日期',
data_dt       VARCHAR(10)         COMMENT       '数据日期（应收日期）',
area_nm       VARCHAR(100)         COMMENT       '片区',
branch_nm       VARCHAR(100)         COMMENT       '分公司',
customer_nm       VARCHAR(50)         COMMENT       '客户名称',
business_id       VARCHAR(50)         COMMENT       '业务编号',
business_type_nm       VARCHAR(50)         COMMENT       '业务类型',
type_nm       VARCHAR(50)         COMMENT       '类型',
out_dt       VARCHAR(10)         COMMENT       '出款日期',
repay_type_nm       VARCHAR(50)         COMMENT       '还款方式',
cur_repay_period       VARCHAR(50)         COMMENT       '当前期数',
borrow_amt       DECIMAL(12,2)         COMMENT       '借款金额',
left_principa_amt       DECIMAL(12,2)         COMMENT       '剩余本金',
max_ovd_days       INT(7)         COMMENT       '最大逾期天数',
cur_ovd_days       INT(7)         COMMENT       '当期逾期天数',
asset_type       VARCHAR(20)         COMMENT       '资产分类',
overdue_stage       VARCHAR(5)         COMMENT       '逾期阶段',
receive_repayment_date       VARCHAR(10)         COMMENT       '应收日期',
receive_principal       DECIMAL(12,2)         COMMENT       '应收本金（元）',
receive_interest       DECIMAL(12,2)         COMMENT       '应收利息（元）',
receive_other_fee       DECIMAL(12,2)         COMMENT       '应收其他费用（元）',
receive_little       DECIMAL(19,2)         COMMENT       '应收小计（本息）',
receive_total       DECIMAL(19,2)         COMMENT       '应收合计（元）',
actual_repayment_date       VARCHAR(10)         COMMENT       '实收日期',
actual_principal       DECIMAL(12,2)         COMMENT       '实收本金（元）',
actual_interest       DECIMAL(12,2)         COMMENT       '实收利息（元）',
actual_other_fee       DECIMAL(12,2)         COMMENT       '实收其他费用（元）',
actual_delaying_payment       DECIMAL(12,2)         COMMENT       '实收滞纳金（元）',
actual_little       DECIMAL(19,2)         COMMENT       '实收小计（本息）',
actual_total       DECIMAL(19,2)         COMMENT       '实收合计（元）',
dw_src_sys       VARCHAR(50)         COMMENT       '来源系统',
dw_src_tbl       VARCHAR(500)         COMMENT       '来源表',
dw_ins_tm       DATETIME         COMMENT       '插入时间',
dw_upd_tm       DATETIME         COMMENT       '更新时间',
dw_ins_usr       VARCHAR(50)         COMMENT       '插入用户',
dw_upd_usr       VARCHAR(50)         COMMENT       '更新用户',
INDEX `idx_dma_ceo_rpt_overdue_detail_business_id` (`business_id`),
INDEX `idx_dma_ceo_rpt_overdue_detail_data_dt` (`data_dt`)

)
COMMENT='ceo看板逾期明细表'
COLLATE='utf8_general_ci';



DROP  TABLE IF EXISTS DMA_CEO_RPT_DATA.dma_ceo_rpt_overdue_detail_his;
CREATE TABLE DMA_CEO_RPT_DATA.dma_ceo_rpt_overdue_detail_his
(
stat_dt       VARCHAR(10)         COMMENT       '跑批日期',
data_dt       VARCHAR(10)         COMMENT       '数据日期（应收日期）',
area_nm       VARCHAR(100)         COMMENT       '片区',
branch_nm       VARCHAR(100)         COMMENT       '分公司',
customer_nm       VARCHAR(50)         COMMENT       '客户名称',
business_id       VARCHAR(50)         COMMENT       '业务编号',
business_type_nm       VARCHAR(50)         COMMENT       '业务类型',
type_nm       VARCHAR(50)         COMMENT       '类型',
out_dt       VARCHAR(10)         COMMENT       '出款日期',
repay_type_nm       VARCHAR(50)         COMMENT       '还款方式',
cur_repay_period       VARCHAR(50)         COMMENT       '当前期数',
borrow_amt       DECIMAL(12,2)         COMMENT       '借款金额',
left_principa_amt       DECIMAL(12,2)         COMMENT       '剩余本金',
max_ovd_days       INT(7)         COMMENT       '最大逾期天数',
cur_ovd_days       INT(7)         COMMENT       '当期逾期天数',
asset_type       VARCHAR(20)         COMMENT       '资产分类',
overdue_stage       VARCHAR(5)         COMMENT       '逾期阶段',
receive_repayment_date       VARCHAR(10)         COMMENT       '应收日期',
receive_principal       DECIMAL(12,2)         COMMENT       '应收本金（元）',
receive_interest       DECIMAL(12,2)         COMMENT       '应收利息（元）',
receive_other_fee       DECIMAL(12,2)         COMMENT       '应收其他费用（元）',
receive_little       DECIMAL(19,2)         COMMENT       '应收小计（本息）',
receive_total       DECIMAL(19,2)         COMMENT       '应收合计（元）',
actual_repayment_date       VARCHAR(10)         COMMENT       '实收日期',
actual_principal       DECIMAL(12,2)         COMMENT       '实收本金（元）',
actual_interest       DECIMAL(12,2)         COMMENT       '实收利息（元）',
actual_other_fee       DECIMAL(12,2)         COMMENT       '实收其他费用（元）',
actual_delaying_payment       DECIMAL(12,2)         COMMENT       '实收滞纳金（元）',
actual_little       DECIMAL(19,2)         COMMENT       '实收小计（本息）',
actual_total       DECIMAL(19,2)         COMMENT       '实收合计（元）',
dw_src_sys       VARCHAR(50)         COMMENT       '来源系统',
dw_src_tbl       VARCHAR(500)         COMMENT       '来源表',
dw_ins_tm       DATETIME         COMMENT       '插入时间',
dw_upd_tm       DATETIME         COMMENT       '更新时间',
dw_ins_usr       VARCHAR(50)         COMMENT       '插入用户',
dw_upd_usr       VARCHAR(50)         COMMENT       '更新用户',
`part_dt` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '分区时间',
INDEX `idx_dma_ceo_rpt_overdue_detail_his_business_id` (`business_id`),
INDEX `idx_dma_ceo_rpt_overdue_detail_his_data_dt` (`data_dt`),
INDEX `idx_dma_ceo_rpt_overdue_detail_his_part_dt` (`part_dt`)

)
COMMENT='ceo看板逾期明细历史表'
COLLATE='utf8_general_ci'
/*!50100 PARTITION BY RANGE (TO_DAYS(part_dt))
(
 PARTITION dma_ceo_rpt_overdue_detail_his_2018_04_08 VALUES LESS THAN (737158) ENGINE = InnoDB,
 PARTITION dma_ceo_rpt_overdue_detail_his_2018_04_09 VALUES LESS THAN (737159) ENGINE = InnoDB,
 PARTITION dma_ceo_rpt_overdue_detail_his_2018_04_10 VALUES LESS THAN (737160) ENGINE = InnoDB,
 PARTITION dma_ceo_rpt_overdue_detail_his_2018_04_11 VALUES LESS THAN (737161) ENGINE = InnoDB,
 PARTITION dma_ceo_rpt_overdue_detail_his_2018_04_12 VALUES LESS THAN (737162) ENGINE = InnoDB,
 PARTITION dma_ceo_rpt_overdue_detail_his_2018_04_13 VALUES LESS THAN (737163) ENGINE = InnoDB,
 PARTITION dma_ceo_rpt_overdue_detail_his_2018_04_14 VALUES LESS THAN (737164) ENGINE = InnoDB,
 PARTITION dma_ceo_rpt_overdue_detail_his_2018_04_15 VALUES LESS THAN (737165) ENGINE = InnoDB,
 PARTITION dma_ceo_rpt_overdue_detail_his_2018_04_16 VALUES LESS THAN (737166) ENGINE = InnoDB,
 PARTITION dma_ceo_rpt_overdue_detail_his_2018_04_17 VALUES LESS THAN (737167) ENGINE = InnoDB,
 PARTITION dma_ceo_rpt_overdue_detail_his_2018_04_18 VALUES LESS THAN (737168) ENGINE = InnoDB,
 PARTITION dma_ceo_rpt_overdue_detail_his_2018_04_19 VALUES LESS THAN (737169) ENGINE = InnoDB,
 PARTITION dma_ceo_rpt_overdue_detail_his_2018_04_20 VALUES LESS THAN (737170) ENGINE = InnoDB,
 PARTITION dma_ceo_rpt_overdue_detail_his_2018_04_21 VALUES LESS THAN (737171) ENGINE = InnoDB,
 PARTITION dma_ceo_rpt_overdue_detail_his_2018_04_22 VALUES LESS THAN (737172) ENGINE = InnoDB,
 PARTITION dma_ceo_rpt_overdue_detail_his_2018_04_23 VALUES LESS THAN (737173) ENGINE = InnoDB,
 PARTITION dma_ceo_rpt_overdue_detail_his_2018_04_24 VALUES LESS THAN (737174) ENGINE = InnoDB,
 PARTITION dma_ceo_rpt_overdue_detail_his_2018_04_25 VALUES LESS THAN (737175) ENGINE = InnoDB,
 PARTITION dma_ceo_rpt_overdue_detail_his_2018_04_26 VALUES LESS THAN (737176) ENGINE = InnoDB,
 PARTITION dma_ceo_rpt_overdue_detail_his_2018_04_27 VALUES LESS THAN (737177) ENGINE = InnoDB,
 PARTITION dma_ceo_rpt_overdue_detail_his_2018_04_28 VALUES LESS THAN (737178) ENGINE = InnoDB,
 PARTITION dma_ceo_rpt_overdue_detail_his_2018_04_29 VALUES LESS THAN (737179) ENGINE = InnoDB,
 PARTITION dma_ceo_rpt_overdue_detail_his_2018_04_30 VALUES LESS THAN (737180) ENGINE = InnoDB,
 PARTITION dma_ceo_rpt_overdue_detail_his_2018_05_01 VALUES LESS THAN (737181) ENGINE = InnoDB,
 PARTITION dma_ceo_rpt_overdue_detail_his_2018_05_02 VALUES LESS THAN (737182) ENGINE = InnoDB,
 PARTITION dma_ceo_rpt_overdue_detail_his_2018_05_03 VALUES LESS THAN (737183) ENGINE = InnoDB) */;