CREATE TABLE `dws_agr_xd_business` (
	`business_id` VARCHAR(50) NULL DEFAULT NULL COMMENT '业务单号',
	`input_time` DATETIME NULL DEFAULT NULL COMMENT '受理时间',
	`customer_id` VARCHAR(50) NULL DEFAULT NULL COMMENT '客户id',
	`customer_name` VARCHAR(50) NULL DEFAULT NULL COMMENT '客户名称',
	`operator_id` VARCHAR(50) NULL DEFAULT NULL COMMENT '主办人编号',
	`business_type` VARCHAR(50) NULL DEFAULT NULL COMMENT '业务类型',
	`original_id` VARCHAR(50) NULL DEFAULT NULL COMMENT '业务获取人编号',
	`branch_id` VARCHAR(50) NULL DEFAULT NULL COMMENT '业务所属分公司编号',
	`area_id` VARCHAR(51) NULL DEFAULT NULL COMMENT '区域编号',
	`wf_id` INT(11) NULL DEFAULT NULL COMMENT '主流程编号',
	`wf_node_id` INT(11) NULL DEFAULT NULL COMMENT '子流程编号',
	`process_id` VARCHAR(50) NULL DEFAULT NULL COMMENT '业务流程编号',
	`business_out_type` INT(11) NULL DEFAULT NULL COMMENT '1为线上费率，0为线下费率',
	`approver_id` VARCHAR(50) NULL DEFAULT NULL COMMENT '最后审批人,用于撤销',
	`apply_repayment_type_id` INT(11) NULL DEFAULT NULL COMMENT '线下出款则为null，还款方式ID，1到期还本息，2每月付息到期还本，5每月等额本息',
	`audit_repayment_type_id` VARCHAR(50) NULL DEFAULT NULL COMMENT '审批还款方式',
	`apply_borrow_money` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '申请借款金额',
	`apply_borrow_limit` INT(11) NULL DEFAULT NULL COMMENT '申请借款期限',
	`audit_borrow_money` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '审批借款金额',
	`audit_borrow_limit` INT(11) NULL DEFAULT NULL COMMENT '审批借款期限',
	`plan_settle_dt` DATETIME NULL DEFAULT NULL COMMENT '计划结清时间',
	`act_settle_dt` DATETIME NULL DEFAULT NULL COMMENT '实际结清时间',
	`repay_status_subtype` INT(11) NULL DEFAULT NULL COMMENT '还款状态类别，详见dim_data.dim_evt_xd_repay_status_subtype',
	`pledge_type` VARCHAR(50) NULL DEFAULT NULL COMMENT '抵押类型',
	`loan_rate` DECIMAL(10,4) NULL DEFAULT NULL COMMENT '年化利率',
	`approve_rate` VARCHAR(50) NULL DEFAULT NULL COMMENT '最终借款利率',
	`flow_branch_id` VARCHAR(50) NULL DEFAULT NULL COMMENT '流程所属分公司编号',
	`business_dept` VARCHAR(50) NULL DEFAULT NULL COMMENT '业务部门',
	`edit_procss_id` VARCHAR(500) NULL DEFAULT NULL COMMENT '已编辑过的节点',
	`customer_type` INT(11) NULL DEFAULT NULL COMMENT '客户类型(0和1为个人借款, 2为企业借款)',
	`after_load_process_id` VARCHAR(50) NULL DEFAULT NULL COMMENT '贷后业务流程编号',
	`after_wf_id` INT(11) NULL DEFAULT NULL COMMENT '贷后主流程编号',
	`after_wf_node_id` INT(11) NULL DEFAULT NULL COMMENT '贷后子流程编号',
	`business_type_detail` VARCHAR(50) NULL DEFAULT NULL COMMENT '[具体业务类型分类]',
	`issue_type` INT(11) NULL DEFAULT NULL COMMENT '发标类型0:线下放款, 1:P2p,2:定期理财',
	`customer_list` VARCHAR(2000) NULL DEFAULT NULL COMMENT '所有客户姓名,已逗号隔开',
	`source_type` TINYINT(4) NULL DEFAULT NULL COMMENT '业务来源：0-常规录入 1-结清续贷新业务 2-结清续贷续贷业务 3-线下历史导入 4-扫码业务 5-优质车抵贷',
	`source_business_id` VARCHAR(50) NULL DEFAULT NULL COMMENT '原始来源业务的业务编号（目前用于结清续贷业务）',
	`issue_split_type` INT(11) NULL DEFAULT NULL COMMENT '标识是否P2P拆标业务，0：非P2P拆标业务，1：P2P拆标业务',
	`is_old` INT(11) NULL DEFAULT NULL COMMENT '1是历史数据，其他不是',
	`is_tuandai_repay` INT(11) NULL DEFAULT NULL,
	`is_extension` INT(11) NULL DEFAULT NULL COMMENT '是否展期 1：是 0：否',
	`first_business_id` VARCHAR(50) NULL DEFAULT NULL COMMENT '原业务编号',
	`Extension_amount` DECIMAL(10,2) NULL DEFAULT NULL COMMENT '展期金额',
	`Renewal_Term` INT(11) NULL DEFAULT NULL COMMENT '展期期限',
	`Rollover_Reimbursement_Means` VARCHAR(50) NULL DEFAULT NULL COMMENT '展期还款方式',
	`Principal_TotalCost` DECIMAL(10,2) NULL DEFAULT NULL COMMENT '本金金额',
	`Interest_TotalCost` DECIMAL(10,2) NULL DEFAULT NULL COMMENT '利息金额',
	`Extension_modify_time` DATETIME NULL DEFAULT NULL COMMENT '展期修改时间',
	`process_modify_time` DATETIME NULL DEFAULT NULL COMMENT '流程修改时间',
	`extension_charges` DECIMAL(10,2) NULL DEFAULT NULL COMMENT '展期手续费',
	`extension_repay_date` DATETIME NULL DEFAULT NULL COMMENT '展期还款日期',
	`original_business_id` VARCHAR(50) NULL DEFAULT NULL COMMENT '当前申请展期的上一次展期编号或者原业务编号',
	`business_after_guid` VARCHAR(50) NULL DEFAULT NULL COMMENT '还款计划批次',
	`Is_Valid` VARCHAR(50) NULL DEFAULT NULL COMMENT '是否有效',
	`dw_src_sys` VARCHAR(50) NULL DEFAULT NULL COMMENT '来源系统',
	`dw_src_tbl` VARCHAR(500) NULL DEFAULT NULL COMMENT '来源表',
	`dw_ins_tm` DATETIME NULL DEFAULT NULL COMMENT '插入时间',
	`dw_upd_tm` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
	`dw_ins_usr` VARCHAR(50) NULL DEFAULT NULL COMMENT '插入用户',
	`dw_upd_usr` VARCHAR(50) NULL DEFAULT NULL COMMENT '更新用户',
	`part_dt` DATETIME NULL DEFAULT NULL COMMENT '分区日期'
)
COMMENT='业务基本信息事实表'
COLLATE='utf8_general_ci'
/*!50100 PARTITION BY RANGE (TO_DAYS(part_dt))
(PARTITION dws_agr_xd_business_2018_02_26 VALUES LESS THAN (737117) ENGINE = InnoDB,
 PARTITION dws_agr_xd_business_2018_02_27 VALUES LESS THAN (737118) ENGINE = InnoDB,
 PARTITION dws_agr_xd_business_2018_02_28 VALUES LESS THAN (737119) ENGINE = InnoDB,
 PARTITION dws_agr_xd_business_2018_03_01 VALUES LESS THAN (737120) ENGINE = InnoDB,
 PARTITION dws_agr_xd_business_2018_03_02 VALUES LESS THAN (737121) ENGINE = InnoDB,
 PARTITION dws_agr_xd_business_2018_03_03 VALUES LESS THAN (737122) ENGINE = InnoDB,
 PARTITION dws_agr_xd_business_2018_03_04 VALUES LESS THAN (737123) ENGINE = InnoDB,
 PARTITION dws_agr_xd_business_2018_03_05 VALUES LESS THAN (737124) ENGINE = InnoDB,
 PARTITION dws_agr_xd_business_2018_03_06 VALUES LESS THAN (737125) ENGINE = InnoDB,
 PARTITION dws_agr_xd_business_2018_03_07 VALUES LESS THAN (737126) ENGINE = InnoDB,
 PARTITION dws_agr_xd_business_2018_03_08 VALUES LESS THAN (737127) ENGINE = InnoDB,
 PARTITION dws_agr_xd_business_2018_03_09 VALUES LESS THAN (737128) ENGINE = InnoDB,
 PARTITION dws_agr_xd_business_2018_03_10 VALUES LESS THAN (737129) ENGINE = InnoDB,
 PARTITION dws_agr_xd_business_2018_03_11 VALUES LESS THAN (737130) ENGINE = InnoDB,
 PARTITION dws_agr_xd_business_2018_03_12 VALUES LESS THAN (737131) ENGINE = InnoDB,
 PARTITION dws_agr_xd_business_2018_03_13 VALUES LESS THAN (737132) ENGINE = InnoDB,
 PARTITION dws_agr_xd_business_2018_03_14 VALUES LESS THAN (737133) ENGINE = InnoDB,
 PARTITION dws_agr_xd_business_2018_03_15 VALUES LESS THAN (737134) ENGINE = InnoDB,
 PARTITION dws_agr_xd_business_2018_03_16 VALUES LESS THAN (737135) ENGINE = InnoDB,
 PARTITION dws_agr_xd_business_2018_03_17 VALUES LESS THAN (737136) ENGINE = InnoDB,
 PARTITION dws_agr_xd_business_2018_03_18 VALUES LESS THAN (737137) ENGINE = InnoDB,
 PARTITION dws_agr_xd_business_2018_03_19 VALUES LESS THAN (737138) ENGINE = InnoDB,
 PARTITION dws_agr_xd_business_2018_03_20 VALUES LESS THAN (737139) ENGINE = InnoDB,
 PARTITION dws_agr_xd_business_2018_03_21 VALUES LESS THAN (737140) ENGINE = InnoDB,
 PARTITION dws_agr_xd_business_2018_03_22 VALUES LESS THAN (737141) ENGINE = InnoDB,
 PARTITION dws_agr_xd_business_2018_03_23 VALUES LESS THAN (737142) ENGINE = InnoDB,
 PARTITION dws_agr_xd_business_2018_03_24 VALUES LESS THAN (737143) ENGINE = InnoDB,
 PARTITION dws_agr_xd_business_2018_03_25 VALUES LESS THAN (737144) ENGINE = InnoDB,
 PARTITION dws_agr_xd_business_2018_03_26 VALUES LESS THAN (737145) ENGINE = InnoDB,
 PARTITION dws_agr_xd_business_2018_03_27 VALUES LESS THAN (737146) ENGINE = InnoDB,
 PARTITION dws_agr_xd_business_2018_03_28 VALUES LESS THAN (737147) ENGINE = InnoDB,
 PARTITION dws_agr_xd_business_2018_03_29 VALUES LESS THAN (737148) ENGINE = InnoDB,
 PARTITION dws_agr_xd_business_2018_03_30 VALUES LESS THAN (737149) ENGINE = InnoDB,
 PARTITION dws_agr_xd_business_2018_03_31 VALUES LESS THAN (737150) ENGINE = InnoDB)  */;
